/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0897c641-ec6b-4165-99f3-4bf234d2afc2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_FRCUZ6hg8",
    "aws_user_pools_web_client_id": "1271kplhat7j2a66q4euosjab8",
    "oauth": {}
};


export default awsmobile;
