/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0897c641-ec6b-4165-99f3-4bf234d2afc2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_FRCUZ6hg8",
    "aws_user_pools_web_client_id": "1271kplhat7j2a66q4euosjab8",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://pzy7n322anfkzlqek7gj2iqthq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-juofddlxjrasjamsmkdlq5vjxm",
    "aws_user_files_s3_bucket": "s3barnholt84953-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
